language: python

services:
  - docker

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
  - docker build -t $DOCKER_USERNAME/terraform-kubectl:latest .
  - docker push $DOCKER_USERNAME/terraform-kubectl:latest
